# Generated by Django 2.2 on 2019-06-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190620_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('NONE', 'None'), ('ENG', 'English'), ('MATH', 'Mathematics'), ('LANG', 'Language'), ('HIST', 'History'), ('SCI', 'Science')], default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(verbose_name='due date'),
        ),
    ]
